config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  resources :properties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nearestrailway.rb
class Nearestrailway < ApplicationRecord
  belongs_to :users
  has_many :properties
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :nearestrailway
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       has_many :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

def About
end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:property, :rent, :address, :building_age, :remarks, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'property list', properties_path, class:"navbar-brand" %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'new property', properties_path, class:"nav-link" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Hello world..</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Notice!</strong>created successfuly
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Property List</title>
    <title>PropertyList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
         <%= render 'layouts/alerts' %>
         <% end %>
      <br/>
    <%= yield %>
</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>

  <div class="field form-group">
    <% form.label :property %>
    <%= form.text_field :property, class:"form-control", placeholder:"Property" %>
  </div>
  <br/>

  <div class="field form-group">
    <% form.label :rent %>
    <%= form.number_field :rent, class:"form-control", placeholder:"Rent" %>
  </div>
  <br/>

  <div class="field form-group">
    <% form.label :address %>
    <%= form.text_field :address, class:"form-control",placeholder:"Address" %>
  </div>
  <br/>

  <div class="field form-group">
    <% form.label :building_age %>
    <%= form.number_field :building_age, class:"form-control", placeholder:"Building age"  %>
  </div>
  <br/>

  <div class="field form-group">
    <% form.label :remarks %>
    <%= form.text_field :remarks, class:"form-control", value:"Remarks" %>
  </div>
  <br/>

  <div class="field form-group">
    <% form.label :user_id %>
    <%= form.number_field :user_id, id: :property_user_id,type: :hidden, class:"form-control", value:current_user.id %>
  </div>



<br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>
<br/>

<%= link_to 'Show', @property, class:"btn btn-secondary" %> 
<%= link_to 'Back', properties_path, class:"btn btn-dark" %>

app/views/properties/index.html.erb
<<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Building age</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.building_age %></td>
        <td><%= property.remarks %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class:"btn btn-secondary" %>

app/views/properties/new.html.erb
<h1>New Property</h1>
<br/>

<%= render 'form', property: @property %>

<br/>
<%= link_to 'Back', properties_path, class:"btn btn-dark" %>

app/views/properties/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @property.property %></h1>
  <p class="lead">
    <%= @property.rent %>|
      <%= @property.address %>|
      <%= @property.building_age %>|
        <%= @property.remarks %>
  </p>
    <%= link_to 'Edit', edit_property_path(@property), class:"btn btn-secondary" %>
  <%= link_to 'Back', properties_path, class:"btn btn-dark" %>
</div>